### 선물하기 등록
### ItemToken1: c694d7ffc7b8431f84162f320b2922ea
### ItemToken2: ca6a803cf613429f91e54fed79360153
POST http://localhost:8081/api/v1/gifts
Content-Type: application/json

{
  "buyerUserId": "12345",
  "payMethod": "TOSS_PAY",
  "pushType": "KAKAO",
  "giftReceiverName": "이기쁨",
  "giftReceiverPhone": "01000001111",
  "giftMessage": "기쁨아 사랑해",
  "orderItemList": [
    {
      "orderCount": 1,
      "itemToken": "{ITEM_TOKEN_HERE}",
      "itemName": "티셔츠",
      "itemPrice": "30000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "사이즈",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "MEDIUM",
              "itemOptionPrice": 0
            }
          ]
        },
        {
          "ordering": 2,
          "itemOptionGroupName": "컬러",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "GOLD",
              "itemOptionPrice": 1000
            }
          ]
        }
      ]
    },
    {
      "orderCount": 1,
      "itemToken": "{ITEM_TOKEN_HERE}",
      "itemName": "양말",
      "itemPrice": "10000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "사이즈",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "LARGE",
              "itemOptionPrice": 0
            }
          ]
        },
        {
          "ordering": 2,
          "itemOptionGroupName": "컬러",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "RED",
              "itemOptionPrice": 0
            }
          ]
        }
      ]
    }
  ]
}

### 선물하기 결제중 상태로 변경
### GiftToken: gt_iNDqT2Q21BxARwCCS
POST http://localhost:8081/api/v1/gifts/{GIFT_TOKEN_HERE}/payment-processing
Content-Type: application/json

### 선물하기 수락 상태로 변경
### GiftToken: gt_iNDqT2Q21BxARwCCS
POST http://localhost:8081/api/v1/gifts/{GIFT_TOKEN_HERE}/accept-gift
Content-Type: application/json

{
  "receiverName": "그렉",
  "receiverPhone": "01000001111",
  "receiverZipcode": "123123",
  "receiverAddress1": "서울시 강동구",
  "receiverAddress2": "우리집",
  "etcMessage": "감사합니다!"
}

### 선물하기 조회
### GiftToken: gt_iNDqT2Q21BxARwCCS
GET http://localhost:8081/api/v1/gifts/{GIFT_TOKEN_HERE}
Content-Type: application/json